### ISSUE TITLE
set a logo on footer of any page ?

### ISSUE THREAD

**Issue by LuisBL** [brechtm/rinohtype#107]
It is possible to set a logo on footer of any page, using directives on template and or style ?

I call `rinoh` like this:

    $ rinoh -s style.rts --template mydoc.rtt doc.rst

with `demo.rtt `:

```
$ more `demo.rtt`
[TEMPLATE_CONFIGURATION]
name = my article template configuration
template = article

[title_page]
show_date = false
$
```

and `style.rts`:

```
$ more style.rts 
[STYLESHEET]
name = My style
base = sphinx_article
# take tags from sphinx.rts
[VARIABLES]
sans_typeface = Helvetica
blue = #20435c
red = #90435c

[heading level 1]
font_color=$(red)
$
```

**Comment by brechtm** [comment]
Technically, this is possible by including an InlineImage in the `footer_text` of a page template configuration. Unfortunately, inline images can currently not be specified in a `.rtt` file. You would have to create a template configuration by creating a Python source file and instantiating `TemplateConfiguration`. Since this also means you cannot use `rinoh` to render your document, this is not very convenient.

I'll look into adding support for specifying inline images in `.rtt` files. It could look something like this:

```
[page]
footer_text = IMAGE('images/footer.pdf', width=0.5in, baseline=20%)
              '\t'
              '{PAGE_NUMBER}'
              '\t'
              '{SECTION_NUMBER(2)}' (section number)
              '{nbsp}{nbsp}{nbsp}'
              '{SECTION_TITLE(2)}' (section title)
```

This would place the image at the left in the footer, the page number in the center and the section number and title at the right.

**Comment by brechtm** [comment]
This feature is now available in the master branch.
