### ISSUE TITLE
NotImplementedError: None:None the 'math' node is not yet supported (rinoh.frontend.rst.nodes)

### ISSUE THREAD

**Issue by kamrankausar** [brechtm/rinohtype#136]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
'rinoh_documents' config variable not set, automatically converting from 'latex_documents'
processing Template... index 
resolving references...
'rinoh_documents' config variable not set, automatically converting from 'latex_documents'
'rinoh_paper_size' config variable not set, automatically converting from 'latex_paper_size'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
rendering... 

Exception occurred:
  File "/home/kamran/anaconda3/lib/python3.6/site-packages/rinoh/frontend/__init__.py", line 32, in map_node
    cls.__module__))
NotImplementedError: None:None the 'math' node is not yet supported (rinoh.frontend.rst.nodes)
The full traceback has been saved in /tmp/sphinx-err-7cf41hgr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by brechtm** [comment]
Unfortunately, rinohtype does not render equations at the moment. At one point, rinohtype could render *some* equations by making use of [matplotlib's equation rendering support](https://matplotlib.org/users/mathtext.html). This was removed somewhere along the way because I was not happy with the quality of the output. However, it could be an option to re-introduce this as a temporary solution.

**Comment by av8r** [comment]
+1
