### ISSUE TITLE
Non-latin characters produce "?" output instead of a proper character

### ISSUE THREAD

**Issue by frol** [brechtm/rinohtype#15]
demo.txt

```
Non-latin characters
====================

Ф - Cyrillyc

검 - Korean

ت - Arabic
```

```
$ rinoh  demo.rst
RinohType 0.1.3-154-g264f (Feb 28 2016, 09:57:09)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
No style 'table of contents title' found in stylesheet
No style 'table of contents title' found in stylesheet
No style 'table of contents title' found in stylesheet
TeXGyrePagella-Regular does not contain glyph for unicode index 0x0424 (Ф)
TeXGyrePagella-Regular does not contain glyph for unicode index 0xac80 (검)
TeXGyrePagella-Regular does not contain glyph for unicode index 0x062a (ت)
TeXGyreHeros-Bold does not contain glyph for unicode index 0x0009 (     )
Writing output: demo.pdf
```

PDF contains:

```
? - Cyrillyc
? - Korean
? - Arabic
```

**Comment by frol** [comment]
I have tried to customize the font since the error message makes me believe that the issue is due to the lack of non-latin characters support in the fonts, but I failed all my attempts to find a proper way to customize it. @brechtm Could you please add an example of doing that?

**Comment by brechtm** [comment]
The fonts are indeed missing the required glyphs. Since 0.3.0, rinohtype uses Deja Vu Serif as a fallback font, but it doesn't include Korean and Arabic glyphs either.

There is only a small selection of fonts available for use with rinohtype for now. Search for ["rinoh-typeface" on PyPI](https://pypi.python.org/pypi?%3Aaction=search&term=rinoh-typeface&submit=search). 

It is fairly easy to create a new font package. You can find the sources for the font packages available from PyPI in [my GitHub repositories](https://github.com/brechtm?tab=repositories&q=rinoh-typeface). The rules for font packages are not documented yet, but here are the basics:

- the entry point name (see `setup.py`) needs to be the same as the typeface name converted to lowercase (so that rinohtype can find the typeface by the name entered in a style sheet file)
- font packages need to be named `rinoh-typeface-<TYPEFACE_ID>`, where `<TYPEFACE_ID>` can be derived from the entry point name using the `entry_point_name_to_identifier` function in [rinoh/resource.py](/brechtm/rinohtype/blob/master/src/rinoh/resource.py) (to allow automatically downloading the font from PyPI and installing it)

In a future release, rinohtype will allow using fonts installed in the operating system as well.

**Comment by frol** [comment]
I see. I have just tested the latest 0.3 release and at least Cyrillic is readable now. Thanks!
