### ISSUE TITLE
`rinoh --format` option is broken ("Unknown format 'reStructuredText'")

### ISSUE THREAD

**Issue by haferburg** [brechtm/rinohtype#284]
http://www.mos6581.org/rinohtype/master/quickstart.html

```
$ rinoh --format reStructuredText demo.txt
Unknown format 'reStructuredText'. Run `rinoh --list-formats` to find out which formats are supported.

$ rinoh --list-formats
Supported input file formats:
- CommonMark (.md) [built-in]
- reStructuredText (.rst) [built-in]
```

What's going on?

I was able to solve it by changing the file extension to .rst. Why not provide a demo.rst in the first place?

**Comment by egamitech** [comment]
It looks like it links to an external file. Perhaps copy the original file in the repo updated as demo.rst or, add a new demo file,  update demo instructions to rename, or update formats to include .txt.

**Comment by brechtm** [comment]
Thanks for the report. This is a regression. In addition to a fix, we need to add a test.

> Why not provide a demo.rst in the first place?

Because docutils already serves this sample file. I guess it could be included in the rinohtype documentation.

> or update formats to include .txt.

Not all .txt files are reStructuredText files, so we can't do that. We could have rinoh feed to file to each of the parsers and go with the first one that doesn't report any syntax errors. Still not fail proof, but it may provide a better user experience nonetheless.

**Comment by brechtm** [comment]
rinoh will now assume reStructuredText if the extension is not known.
