### ISSUE TITLE
Encoding issue in demo.txt?

### ISSUE THREAD

**Issue by haferburg** [brechtm/rinohtype#286]
http://www.mos6581.org/rinohtype/master/quickstart.html links to https://docutils.sourceforge.io/docs/user/rst/demo.txt which has the following text
![image](https://user-images.githubusercontent.com/4941909/131320538-211ecf16-a5cc-4a50-adaf-b60b284eb063.png)

```
The `â€œmetaâ€ directive`__ is used to specify metadata to be stored in,
e.g., HTML META tags or ODT file properties.
```

and this renders out to 
![image](https://user-images.githubusercontent.com/4941909/131321051-7975aa68-4274-4d4a-af90-24b67640c1a0.png)

**Comment by brechtm** [comment]
Thanks for the detailed report!

Those are supposed to be double quotes. Opening up that link in Firefox, shows the same as your first screenshot. Downloading the file and opening it with less, VSCode and other applications shows the proper quotes.

Rendering the file with _rinoh_ also produces the correct quotes. I suspect this is another Windows-specific issue. AFAIK, Python on Windows defaults to opening files in an encoding different from UTF-8, unlike other platforms. _rinoh_ should probably always open files as UTF-8 (we could provide an additional command line option to force a particular encoding). I wonder what Sphinx does...

We need to add a regression test for this as well.

**Comment by brechtm** [comment]
demo.txt renders properly on Windows for me. I think this depends on how you downloaded that file. As I mentioned above, opening that URL in Firefox, I see the same characters as in your screenshot. Saving it to disk using Firefox or wget, the file does contains the correct characters (quotes).

I think this happens because SourceForge doesn't supply content-type or content-encoding headers when serving demo.txt, leaving it up to the application to decide which encoding to use. Your screenshot looks like cp1252 encoding was assumed. Perhaps you copy-pasted the contents into a file instead of downloading it?
