### ISSUE TITLE
Customising the title page

### ISSUE THREAD

**Issue by techauthoruk** [brechtm/rinohtype#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

I know this was raised in #157 but wondered if there had been any progress?

I too would prefer to have 'version' rather than 'release' (or have the option to choose?). In similar vein, is it possible to append text in front of the date? I would like to add something like 'Issue date: ' and then the date.

I can edit the final file in Acrobat, but it would be good to be able to do this without resorting to using Acrobat.

**Comment by brechtm** [comment]
> I too would prefer to have 'version' rather than 'release' (or have the option to choose?).

If you set _subtitle_ in the [`rinoh_documents`](http://www.mos6581.org/rinohtype/master/sphinx.html#confval-rinoh_documents) entry, it will override the default document subtitle.

> In similar vein, is it possible to append text in front of the date? I would like to add something like 'Issue date: ' and then the date.

You can pre/append arbitrary text to any document element from the style sheet. For the date on the title page, the _title page date_ style is already defined, so you can simply set _before_ for this element.

```ini
[title page date]
before = 'Issue date: ' (title page date prefix)
; note that you can also omit elements from the output by setting its 'hide' attribute
; hide = true

[title page date prefix : StyledText('title page date prefix')]
font_weight = bold
font_color = #aaa
```

The `(title page date prefix)` following the _before_ text sets that text's _style_ to _title page date prefix_, which is then used in the next style definition to apply some custom styling. This is yet another thing to be documented :-)

P.S. You are welcome to add a comment to an existing issue in this case instead of opening a new issue.

**Comment by techauthoruk** [comment]
WOW!!!!!!

Amazing - thank you @brechtm this has solved my issue. I am just blown away with the capabilities of rinohtype with Sphinx. It makes my life so much easier!

Closing this now as my issue is resolved.

**Comment by brechtm** [comment]
> Amazing - thank you @brechtm this has solved my issue. I am just blown away with the capabilities of rinohtype with Sphinx. It makes my life so much easier!

With the exception of all the bugs you're running into! 🤣

**Comment by techauthoruk** [comment]
To be fair, most of the issues I am coming across aren't bugs, just my lack of knowledge of reST, LaTeX, Sphinx, and rinohtype!

It's a learning curve, but one that is proving very rewarding!
