### ISSUE TITLE
Extra blank pages are inserted

### ISSUE THREAD

**Issue by pcav** [brechtm/rinohtype#59]
at the end of each chapter, apparently. see docs sent in private

**Comment by brechtm** [comment]
This is a feature of the book template. To make new chapters start on right-hand pages, chapters end at a left-hand page, using a blank page if necessary.

You can override this behavior by setting the [`end_at_page`](http://www.mos6581.org/rinohtype/api/template.html#rinoh.template.DocumentPartTemplate.end_at_page) in your template configuration.

**Comment by pcav** [comment]
I'm aware of this, but in my tests there are more blank pages in rinoh than in Sphinx, for the same input.

**Comment by brechtm** [comment]
I had another look at `EGGgrid_latex.pdf` and `EGGgrid_rinohtype.pdf`. The first three chapters are very similar so that chapters 1, 2, 3 and 4 start on the same page in both the LaTeX and rinohtype output.

Due to differences in rendering, chapter 4 is a little bit longer in the rinohtype output. A blank page is inserted to make chapter 5 start on a right-hand page. As rinohtype will never be able to produce the exact same output as LaTeX (because that is not a goal), this is all considered normal.

There is something strange going on at the end of chapter 5. There are three blank pages following the text, and some of them have no or strange headers/footers. I suspect this is because of the "Python Module Index". Can you verify with rinohtype 0.3.0?

**Comment by pcav** [comment]
Confirmed, it seems to work fine here. Thanks!
