### ISSUE TITLE
Exception raised trying to build from sphinx

### ISSUE THREAD

**Issue by zondo** [brechtm/rinohtype#99]
Here's what I got:

`  File "C:\Python34\lib\site-packages\rinoh\frontend\__init__.py", line 41, in __getattr__
    raise AttributeError('No such element: {} in {}'.format(name, self))
AttributeError: No such element: styled_text in <rinoh.frontend.rst.nodes.Raw object at 0x06CEECF0>
`

**Comment by brechtm** [comment]
I suppose the source contains a custom interpreted text role derived from the raw role? Can you share the Sphinx project you are trying to render, or at least the part where the custom role is defined and used?

**Comment by zondo** [comment]
Certainly can -- it's [here](https://github.com/i6/ibg) on github.  The conf.py doesn't have the rinohtype extension yet, so you'll have to add it.

**Comment by brechtm** [comment]
The project will build with the fix applied in b5d94f61629815eaa2e2d34f86915e4fe0428239 (to be part of 0.3.2).

Note that rinohtype will not render the LaTeX-specific raw roles of course. You should probably avoid using these. Features such as drop caps should really be handled by configuring the builder (not that it is supported by rinohtype at this moment).

The Sphinx project has some problems BTW. Building the HTML documentation fails because the path to `logo.png` is incorrect.
